import type { TimelineState } from "@ty/Schema";

const now = new Date();

export const timelineTemplates: TimelineState[] = [
  {
    id: "001",
    summary: "DJ: Full Wedding (Ceremony, Reception, & Dancing)",
    date: new Date("2026-03-01"),
    date_modified: new Date("2026-03-01"),
    date_created: new Date("2026-03-01"),
    date_civil: "2026-03-01",
    timezone: "America/Chicago",
    start: 0,
    end: 0,
    rev: 1,
    moments: [
      {
        id: 1,
        start: 960,
        end: 990,
        desc: "Pre-Seating Music",
        skill_id: 3,
        group_id: 1,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 2,
        start: 990,
        end: 1005,
        desc: "Presession of Ceremony",
        skill_id: 2,
        group_id: 1,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 3,
        start: 1005,
        end: 1020,
        desc: "Recession of Ceremony",
        skill_id: 2,
        group_id: 1,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 4,
        start: 1050,
        end: 1110,
        desc: "Cocktail Hour",
        skill_id: 3,
        group_id: 2,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 5,
        start: 1110,
        end: 1125,
        desc: "Introductions",
        skill_id: 1,
        group_id: 3,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 6,
        start: 1120,
        end: 1125,
        desc: "Cake Cutting",
        skill_id: 2,
        group_id: 4,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 7,
        start: 1125,
        end: 1140,
        desc: "Blessing",
        skill_id: 1,
        group_id: 5,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 8,
        start: 1125,
        end: 1200,
        desc: "Dinner Music",
        skill_id: 3,
        group_id: 2,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 9,
        start: 1170,
        end: 1185,
        desc: "Toasts",
        skill_id: 1,
        group_id: 4,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 10,
        start: 1200,
        end: 1215,
        desc: "Traditional Dances",
        skill_id: 2,
        group_id: 4,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 11,
        start: 1260,
        end: 1275,
        desc: "Bouquet and Garter Toss",
        skill_id: 2,
        group_id: 4,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 12,
        start: 1215,
        end: 1380,
        desc: "Open Dancefloor",
        skill_id: 3,
        group_id: 3,
        timeline_uuid: "001",
        note: "",
      },
    ],
    steps: [
      {
        id: 101,
        moment_id: 10,
        tbd: false,
        note: "",
        text: "Jerry & Kim (Father & Daughter)",
        order: 0,
      },
      {
        id: 102,
        moment_id: 10,
        tbd: false,
        note: "",
        text: "Hannah & Kevin (Mother & Son)",
        order: 0,
      },
      {
        id: 103,
        moment_id: 10,
        tbd: false,
        note: "",
        text: "Kim & Kevin (First Dance)",
        order: 0,
      },
      {
        id: 104,
        moment_id: 10,
        tbd: false,
        note: "",
        text: "",
        order: 0,
      },
      {
        id: 105,
        moment_id: 10,
        tbd: false,
        note: "",
        text: "",
        order: 0,
      },
      {
        id: 91,
        moment_id: 9,
        tbd: false,
        note: "",
        text: "Jerry (FOB)",
        order: 0,
      },
      {
        id: 92,
        moment_id: 9,
        tbd: false,
        note: "",
        text: "Sara (Matron of Honor)",
        order: 0,
      },
      {
        id: 93,
        moment_id: 9,
        tbd: false,
        note: "",
        text: "Brendan (Best Man)",
        order: 0,
      },
      {
        id: 94,
        moment_id: 9,
        tbd: false,
        note: "",
        text: "",
        order: 0,
      },
      {
        id: 51,
        order: 1,
        moment_id: 5,
        tbd: false,
        note: "",
        text: "Brendan & Sara",
      },
      {
        id: 52,
        order: 2,
        moment_id: 5,
        tbd: false,
        note: "",
        text: "Rachele & Harry",
      },
      {
        id: 53,
        order: 3,
        moment_id: 5,
        tbd: true,
        note: "",
        text: "TBD Tom (or Brett) & Jessica",
      },
    ],
    groups: [
      {
        id: 1,
        name: "Ceremony",
        timeline_uuid: "001",
      },
      {
        id: 2,
        name: "Reception",
        timeline_uuid: "001",
      },
      {
        id: 3,
        name: "Introductions",
        timeline_uuid: "001",
      },
      {
        id: 4,
        name: "Traditionals",
        timeline_uuid: "001",
      },
      {
        id: 5,
        name: "Dancing",
        timeline_uuid: "001",
      },
    ],
    skills: [
      {
        name: "MC Announcement",
        icon: "🎤",
        color: "hotpink",
        id: 1,
        timeline_uuid: "001",
      },
      {
        name: "Song Cue",
        icon: "♪",
        color: "limegreen",
        id: 2,
        timeline_uuid: "001",
      },
      {
        name: "Music Playlist",
        icon: "🎶",
        color: "cornflowerblue",
        id: 3,
        timeline_uuid: "001",
      },
      { name: "Misc", icon: "⎑", color: "", id: 4, timeline_uuid: "001" },
    ],
  },
  {
    id: "002",
    summary: "DJ: Bar/Bat Mitzvah",
    date: now,
    date_modified: now,
    date_created: now,
    date_civil: now.toLocaleDateString("en-CA"),
    timezone: "America/Chicago",
    start: 0,
    end: 0,
    rev: 1,
    moments: [
      {
        desc: "Cocktail Hour",
        timeline_uuid: "003",
        note: "",
        start: 900,
        end: 960,
        skill_id: 9,
        group_id: 10,
        id: 13,
        tbd: false,
      },
      {
        start: 960,
        end: 975,
        desc: "Introductions",
        skill_id: 8,
        group_id: 9,
        note: "",
        tbd: false,
        timeline_uuid: "003",
        id: 14,
      },
      {
        start: 990,
        end: 1005,
        desc: "Game #1 Trivia",
        skill_id: 7,
        group_id: 7,
        note: "TBD prizes?",
        tbd: true,
        timeline_uuid: "003",
        id: 15,
      },
      {
        start: 1005,
        end: 1050,
        desc: "Dance Break #1",
        skill_id: 9,
        group_id: 8,
        note: "",
        tbd: false,
        timeline_uuid: "003",
        id: 16,
      },
      {
        start: 1050,
        end: 1110,
        desc: "Dinner Served",
        skill_id: 9,
        group_id: 10,
        note: "",
        tbd: false,
        timeline_uuid: "003",
        id: 17,
      },
      {
        start: 1110,
        end: 1140,
        desc: "Game #2 Snowball",
        skill_id: 7,
        group_id: 7,
        note: "No prize needed",
        tbd: false,
        timeline_uuid: "003",
        id: 18,
      },
      {
        start: 1155,
        end: 1185,
        desc: "Dance Break #2",
        skill_id: 9,
        group_id: 8,
        note: "",
        tbd: false,
        timeline_uuid: "003",
        id: 19,
      },
      {
        start: 1185,
        end: 1215,
        desc: "Game #3 Pepsi Coke ",
        skill_id: 7,
        group_id: 7,
        note: "grand prize for the pair of winners (possible runner up prize for 2nd place pair)",
        tbd: false,
        timeline_uuid: "003",
        id: 20,
      },
      {
        start: 1215,
        end: 1230,
        desc: "The Hora",
        skill_id: 8,
        group_id: 9,
        note: "traditional or modern song choice?",
        tbd: true,
        timeline_uuid: "003",
        id: 21,
      },
      {
        start: 1230,
        end: 1290,
        desc: "Final Stretch",
        skill_id: 9,
        group_id: 10,
        note: "",
        tbd: false,
        timeline_uuid: "003",
        id: 22,
      },
      {
        start: 1140,
        end: 1155,
        desc: "Dance With Parent",
        skill_id: 8,
        group_id: 9,
        note: "",
        tbd: false,
        timeline_uuid: "003",
        id: 23,
      },
      {
        start: 975,
        end: 980,
        desc: "Speech from Parents",
        skill_id: 7,
        group_id: 9,
        note: "",
        tbd: false,
        timeline_uuid: "003",
        id: 24,
      },
    ],
    steps: [
      {
        text: "Parents ",
        tbd: false,
        moment_id: 14,
        note: "",
        order: 1,
        id: 106,
      },
      {
        text: "Guest of Honor",
        tbd: false,
        moment_id: 14,
        note: "",
        order: 1,
        id: 107,
      },
      {
        text: "List of Questions and answers",
        tbd: true,
        moment_id: 15,
        note: "",
        order: 1,
        id: 108,
      },
      {
        text: "Prize Givaways (for each question or for person with highest points?)",
        tbd: false,
        moment_id: 15,
        note: "",
        order: 1,
        id: 109,
      },
    ],
    groups: [
      {
        name: "Games",
        timeline_uuid: "003",
        id: 7,
      },
      {
        name: "Dancing",
        timeline_uuid: "003",
        id: 8,
      },
      {
        name: "Traditionals",
        timeline_uuid: "003",
        id: 9,
      },
      {
        name: "Reception",
        timeline_uuid: "003",
        id: 10,
      },
    ],
    skills: [
      {
        name: "MC",
        icon: "🎤",
        color: "#ff00b8",
        timeline_uuid: "003",
        id: 7,
      },
      {
        name: "Song Cue",
        icon: "♪",
        color: "#00ed00",
        timeline_uuid: "003",
        id: 8,
      },
      {
        name: "Music Playlist",
        icon: "🎶",
        color: "#00c7e9",
        timeline_uuid: "003",
        id: 9,
      },
      {
        name: "Misc",
        icon: "☘",
        color: "#808080",
        timeline_uuid: "003",
        id: 10,
      },
    ],
  },
  {
    id: "003",
    summary: "DJ: Corporate Event",
    date: now,
    date_modified: now,
    date_created: now,
    date_civil: now.toLocaleDateString("en-CA"),
    timezone: "America/Chicago",
    start: 0,
    end: 0,
    rev: 1,
    moments: [
      {
        desc: "Arriving Background Music",
        timeline_uuid: "003",
        note: "light adult contemporary",
        start: 540,
        end: 660,
        skill_id: 9,
        group_id: 7,
        id: 25,
      },
      {
        start: 660,
        end: 675,
        desc: "Opening Remarks",
        skill_id: 1,
        group_id: 8,
        note: "",
        tbd: false,
        timeline_uuid: "003",
        id: 26,
      },
      {
        desc: "Lunch",
        timeline_uuid: "003",
        note: "Same as arrival music",
        start: 675,
        end: 750,
        skill_id: 9,
        group_id: 8,
        id: 27,
      },
      {
        desc: "Breakout Sessions",
        timeline_uuid: "003",
        note: "Provide music to 2 classrooms",
        start: 750,
        end: 810,
        skill_id: 9,
        group_id: 8,
        id: 28,
      },
      {
        desc: "Panel Discussion",
        timeline_uuid: "003",
        note: "",
        start: 810,
        end: 870,
        skill_id: 7,
        group_id: 8,
        id: 29,
      },
      {
        desc: "Keynote Speaker",
        timeline_uuid: "003",
        note: "",
        start: 870,
        end: 900,
        skill_id: 7,
        group_id: 9,
        id: 35,
      },
      {
        desc: "Raffle",
        timeline_uuid: "003",
        note: "upbeat and energetic",
        start: 900,
        end: 960,
        skill_id: 9,
        group_id: 9,
        id: 36,
      },
      {
        desc: "Closing Remarks",
        timeline_uuid: "003",
        note: "",
        start: 960,
        end: 975,
        skill_id: 7,
        group_id: 8,
        id: 37,
      },
    ],
    steps: [],
    groups: [
      {
        name: "Arrival",
        timeline_uuid: "003",
        id: 7,
      },
      {
        name: "Reception",
        timeline_uuid: "003",
        id: 8,
      },
      {
        name: "Special",
        timeline_uuid: "003",
        id: 9,
      },
      {
        name: "Misc",
        timeline_uuid: "003",
        id: 10,
      },
    ],
    skills: [
      {
        name: "MC",
        icon: "🎤",
        color: "#ff00b8",
        timeline_uuid: "003",
        id: 7,
      },
      {
        name: "Song Cue",
        icon: "♪",
        color: "#00ed00",
        timeline_uuid: "003",
        id: 8,
      },
      {
        name: "Music Playlist",
        icon: "🎶",
        color: "#00c7e9",
        timeline_uuid: "003",
        id: 9,
      },
      {
        name: "Misc",
        icon: "☘",
        color: "#808080",
        timeline_uuid: "003",
        id: 10,
      },
    ],
  },
  {
    id: "004",
    summary: "Start from Scratch",
    date: now,
    date_modified: now,
    date_created: now,
    date_civil: now.toLocaleDateString("en-CA"),
    timezone: "America/Chicago",
    start: 0,
    end: 0,
    rev: 1,
    moments: [],
    steps: [],
    groups: [],
    skills: [],
  },
];
