import type { TimelineState } from "@ty/Schema";

export const timelineTemplates: TimelineState[] = [
  {
    id: "003",
    summary: "Full Wedding (Ceremony, Reception, & Dancing)",
    date: new Date("2026-03-01"),
    date_modified: new Date("2026-03-01"),
    date_created: new Date("2026-03-01"),
    date_civil: "2026-03-01",
    timezone: "America/Chicago",
    start: 0,
    end: 0,
    rev: 1,
    moments: [
      {
        id: 1,
        start: 960,
        end: 990,
        desc: "Pre-Seating Music",
        skill_id: 3,
        group_id: 1,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 2,
        start: 990,
        end: 1005,
        desc: "Presession of Ceremony",
        skill_id: 2,
        group_id: 1,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 3,
        start: 1005,
        end: 1020,
        desc: "Recession of Ceremony",
        skill_id: 2,
        group_id: 1,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 4,
        start: 1050,
        end: 1110,
        desc: "Cocktail Hour",
        skill_id: 3,
        group_id: 2,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 5,
        start: 1110,
        end: 1125,
        desc: "Introductions",
        skill_id: 1,
        group_id: 3,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 6,
        start: 1120,
        end: 1125,
        desc: "Cake Cutting",
        skill_id: 2,
        group_id: 4,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 7,
        start: 1125,
        end: 1140,
        desc: "Blessing",
        skill_id: 1,
        group_id: 5,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 8,
        start: 1125,
        end: 1200,
        desc: "Dinner Music",
        skill_id: 3,
        group_id: 2,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 9,
        start: 1170,
        end: 1185,
        desc: "Toasts",
        skill_id: 1,
        group_id: 4,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 10,
        start: 1200,
        end: 1215,
        desc: "Traditional Dances",
        skill_id: 2,
        group_id: 4,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 11,
        start: 1260,
        end: 1275,
        desc: "Bouquet and Garter Toss",
        skill_id: 2,
        group_id: 4,
        timeline_uuid: "001",
        note: "",
      },
      {
        id: 12,
        start: 1215,
        end: 1380,
        desc: "Open Dancefloor",
        skill_id: 3,
        group_id: 3,
        timeline_uuid: "001",
        note: "",
      },
    ],
    steps: [
      {
        id: 101,
        moment_id: 10,
        tbd: false,
        note: "",
        text: "Jerry & Kim (Father & Daughter)",
        order: 0,
      },
      {
        id: 102,
        moment_id: 10,
        tbd: false,
        note: "",
        text: "Hannah & Kevin (Mother & Son)",
        order: 0,
      },
      {
        id: 103,
        moment_id: 10,
        tbd: false,
        note: "",
        text: "Kim & Kevin (First Dance)",
        order: 0,
      },
      {
        id: 104,
        moment_id: 10,
        tbd: false,
        note: "",
        text: "",
        order: 0,
      },
      {
        id: 105,
        moment_id: 10,
        tbd: false,
        note: "",
        text: "",
        order: 0,
      },
      {
        id: 91,
        moment_id: 9,
        tbd: false,
        note: "",
        text: "Jerry (FOB)",
        order: 0,
      },
      {
        id: 92,
        moment_id: 9,
        tbd: false,
        note: "",
        text: "Sara (Matron of Honor)",
        order: 0,
      },
      {
        id: 93,
        moment_id: 9,
        tbd: false,
        note: "",
        text: "Brendan (Best Man)",
        order: 0,
      },
      {
        id: 94,
        moment_id: 9,
        tbd: false,
        note: "",
        text: "",
        order: 0,
      },
      {
        id: 51,
        order: 1,
        moment_id: 5,
        tbd: false,
        note: "",
        text: "Brendan & Sara",
      },
      {
        id: 52,
        order: 2,
        moment_id: 5,
        tbd: false,
        note: "",
        text: "Rachele & Harry",
      },
      {
        id: 53,
        order: 3,
        moment_id: 5,
        tbd: true,
        note: "",
        text: "TBD Tom (or Brett) & Jessica",
      },
    ],
    groups: [
      {
        id: 1,
        name: "Ceremony",
        timeline_uuid: "001",
      },
      {
        id: 2,
        name: "Reception",
        timeline_uuid: "001",
      },
      {
        id: 3,
        name: "Introductions",
        timeline_uuid: "001",
      },
      {
        id: 4,
        name: "Traditionals",
        timeline_uuid: "001",
      },
      {
        id: 5,
        name: "Dancing",
        timeline_uuid: "001",
      },
    ],
    skills: [
      {
        name: "MC Announcement",
        icon: "🎤",
        color: "hotpink",
        id: 1,
        timeline_uuid: "001",
      },
      {
        name: "Song Cue",
        icon: "♪",
        color: "limegreen",
        id: 2,
        timeline_uuid: "001",
      },
      {
        name: "Music Playlist",
        icon: "🎶",
        color: "cornflowerblue",
        id: 3,
        timeline_uuid: "001",
      },
      { name: "Misc", icon: "⎑", color: "", id: 4, timeline_uuid: "001" },
    ],
  },
];
